language: java

env:
  global:
  - secure: 0ciJ7NIOPV3gvjDXXMsUnHRsZcdAr7i1kN+DQPFk9YQhVj0NHw4wiZbee4FZmUb5o9NlPihnTd0mECO3PSWbVMVnwffaIXmy6zvj/Y2LYP8RFcDrd6bonx+oaLtuF/twcnePujmMWgB8OxDHF1tfJiDGVcJxYeA4Gg0WbFjHxDU02yKYB5Bfa+omG9n/X8vf5K++5ZL6b2TPLRGvcI5ORgTofqWVHR7jIDOyyTxku1ufB9PRTrka8sN0vOCOdOffofvbtK4qv8J66m2s0gNq186JlFKEkRbPD8zmEb4XQ/Mm+BjR3wSkDPBc72FzqVwHcS64CfkXUQV0s5JFzZw7sUARH2HBhjJaU9XiXU3WofdJif4Wk7sGFvN3wRsrrelE54gJ3T0vrs9gTmHiEQyejlP87NgUY17ECZWsQfj4xlV3hOdHvwvOH4/cvKSyQvUI9P9X/XH9jv64V24akVOfZRxwDw1cYOu4lzdgyRZb10ybfxJhQJ218ncA0QpoGSkw6WLv1475/juy3DJJTElj32/DaVxzYGUWwaPNZxL+TsrSl3NoGIagA5L8mVfgZFwKMMyLgcQHTFcVwY1jyfw5eBN1CW/mEM1KrGPYFWStvDh264RvxydbuCWjSHFrWWVZSwhw9Kk2+t08IW1ncuTUlEw0Ynb6Mk2oGNppFrdc2Y0=
  - secure: eOB8pqIqgMfZbw64N6G4thg+ZUt60bAQcxoSqbU4PKMyyC0C9PmCQzqsLr7g/7ScSXKDAGh/CJIVZYqwOA22GNvqAXOljxXlcD6Y8GCRXx9uJJ2XA02NUpNmozeDNUXhIGdeaZREyoDUZgEJ5J0CLM+sYEBFA4ro5WEnRMcwTGa2QRI5wRDkKcSnWj2VF04YDDISRNdzUb4pynHJTwc4xnS+opIhpWqOZJsjWB28TgOSYidbgeI4OSQbnDthXmVi9iSkGHLyMlWC5hIrGrn6PiSkODxOpYYRhC3klnn2/SncWhvlLRkIMSq6I9Y6fcMQ9ME2+Vo7csbIFtb9+f3Q6tYcbcB9dn3IyZ08IfZZI4MHS1UGA4wCTAjOamoN230xXw9EF5PxcEbvBh7HMvbliNOrKZI8O9OXvOuRSPcVyrtj0GXSlr9BkVkrDLOKJ5xc3uSvekelab5X0uWVCUSk0GZovPVbhM6o/rJ+rnCg582U/BfG2ow1ERCBMXQZtBH2rxCTokCC1AWsBEh1pd7JdwW82sDXTBcCBaNCbi7Y1RMfpHQgdE2LbphVeFfIIPES9Q7xMUithONGO8Lv5iZ1Bw/N++1YWLDDgfRQE3CvvSOF4OQDW4AdSsqX9zLxtKxn82GXwSxWHo9By/8xE45NYE/joi0Kj+ptNZZx6ylft1U=
  - secure: JcyTGExVgqoN3+k/KerQqpsaZ6yZsnWWAabhpVy4VY529HEXfxXl9SpKbpibiKLaLAg88W+o813Chpa+rN6rmeMga3HvB5kBZodwGJY8MnuvQutD5Uu3+wxHqbq0O99LMmpi4W3OZA9K1A/EXgPMhyvq4QeZncr8JIG8K9sN+Yep7sXnfYUC7ODzh4CiAlW3a6dEgXgE8tda8dKXgta06EtLUTiNU42HuiDNIyApylXWhZ8ba8+0Yx6XbB/S1ekgUy8U1IxmnZplcrgf3hwEZ1C771BTfzb8Nr1RJI5IOSe5SXzDBwRLOgtaAQ8HavvazMgNw+leCwvPfAu/wkjgGqkG9uYCS7jUmidevNJrjfS3PUqtBDYnxJFS2HRM2lKRYGW7RimPAgZstrOhXr+bxqaJjR7bOWvVh88D4CgGqU7BDj9yVwZSvEJ/o2HhPqw3wEYe2VoI7J55JpSR82zPdPE+VVxlGXBtGJcqeiA9lsWwWRaE6oQhtnF2CIbz5sMPREjtoOb+evVqvjhfr+71z6gOQ5mr+FkMaJ1U+Vj+NYPpMVU9EAI0al+hC3iT358bICvzTjOiqX6ucJj8koU/vFyVxgdbctwNST+vatNnndBSXQ8NntZ6gPj1GZaEX8S+R7TLAC9daN/AAfNcDXsdSmzhBeQAQ+lIQFAiRSiRdMo=
  - secure: ocWWwrWFlrt20Snrpclgc5lJA6HrB0Rioyub5msdYY1zds1sUvFghXxoxbgDMN+tVChRbJWrlHcm7XfIJ5XTqql/mEu5gX/EdR8MjKVQ7vPFHpL8Ts4fbMtrsZrMdSfQ9QV3uFRzGzw6QSNL+VwFWKHbITWyayHbZUWER9pYVRWOIjz9PQmOY8REkv+EK6yY/oKR6X0FjxJD9U1mM3p4mqKqIb3WuvpUElGn/B32zp7cbXnk8QqrevxEb1TGuvoA8hw2hEnqkTe6a0eT6sJ0QjZf6FeITVFSS74bfT02gDK+fCMOfSbHa51ArU4Htn3j8UR9jpl4Kl3kOI2bNpeh3psh6LfEA8SY+fHKIPCBMc2AV6fXGyleOG6il8ntj5FkDhC/1GbLuJgnHVkaOU/hjpkBIqlfz0fX5LiglryfD2GGPgAzV0errdFsYFRWZOeBf3SoUr+PBtzHuuX+f6l+Tln3O/2QPapNuyxoeezU1q5vZyBFvd0fMSfml9VJsA5uPxxXRHuUrEMbkIAzMS9ZrYn483AOawU+U287dTHCXrJKQ2J9gj2fjKITsfHVfMIK84TfIdUx2kOb9HUsWgYPpsQlRZPDGo35YaEGLpgOPrF8q52DBO6ljagh+hC1hcAXgzFrriR6/7LBaItYNZxCr5WGaKyXGWyJak1H6nGM4+8=
  - secure: qWIHmou/IZcasB4O3vNAA385cx23XWEmViPwmGNizlnz3lcn4Kwem6d+arOD4BV9F+iPCZjnU5N6BPP7Dq5w+lvbNGrCq1vrCS3Ms85SjEB3voalb+/ZmaGw9DvQfDEcRcdP8Wfi/5HgoOZa4Gex9oC66lJ73iS6RMPcFDPzs/dUt20EStVNcu4I0I+OkjJdFaduO1hXuFHe5RnUGCOKLZvb0hXTSHG1bYkgDXrQZ4Kf9+/NXyku7kZ2pEPAZAsQ2dE/dtWtrUrwmtfGGWhEWqpR+0WSnlopoeC8QhDx7n3bBX7G39WXzBfbFlzJ5QMtdudugXtsf9KJtv2eiSBu5ZKOz5GGqTOqIG5PxVYSH/mRftA5cM0juU1r5HIot3TTqGqmwVzQ5ICwHGyvcgEK3yntH0A9dkzwSGllM56+wFrhD+0GvTCRgd47Tgygtly9MKQ6HqFHp+GqRsJ8+sZFcZX1URi8ioQVWttIcrdTzh6pGtdrjG1KAM7f6AVauTd4tbhVx2++lOJ2WO1xaWco7hixoFSsyo+VuN6FQXQ6jkCgBGh8GtQ43m2zflWAHWwC6z5epKpJ4ZGbE7CiogRpucFY2tBoXa8kiiS3MWCRXS9Kf9osJMSArszMHxgJPQ3ukVOGy+B20fpjxh3bh/u8gVdpQsv+s5dMDc3O5d2EwNI=

jdk:
- oraclejdk8

before_deploy: openssl aes-256-cbc
  -K $encrypted_2e5d7b621c46_key
  -iv $encrypted_2e5d7b621c46_iv
  -in secring.gpg.enc
  -out secring.gpg -d

deploy:
- provider: script
  script: ./gradlew uploadArchives
    -PossrhUsername='$SONATYPE_USERNAME'
    -PossrhPassword='$SONATYPE_PASSWORD'
    -Psigning.keyId='$SIG_KEY'
    -Psigning.password='$SIG_PASS'
    -Psigning.secretKeyRingFile='$SIG_FILE'
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: ./gradlew uploadArchives
    -PossrhUsername='$SONATYPE_USERNAME'
    -PossrhPassword='$SONATYPE_PASSWORD'
    -Psigning.keyId='$SIG_KEY'
    -Psigning.password='$SIG_PASS'
    -Psigning.secretKeyRingFile='$SIG_FILE'
  skip_cleanup: true
  on:
    tags: true
    branch: master
